### ISSUE TITLE
WASM Executable from NodeJS

### ISSUE THREAD

**Issue by loretoparisi** [vshymanskyy/wasm2native#1]
Hello, I have [this](https://github.com/loretoparisi/fasttext.js/) project that supports WASM module as alternative.
The module [here](https://github.com/loretoparisi/fasttext.js/tree/master/wasm) needs an external resource file to run, files requested are the following

```
fasttext.js (api header)
fasttext_wasm.js (wasm loader)
lid.176.ftz (resource/model file to load)
```

Is it possibile to use `wasm2native` to compile and bundle these three files to one executable file?

Thank you.

**Comment by vshymanskyy** [comment]
No, it's not possible with `wasm2native`, as it requires a JS engine.
So at the end of the day, you need to bundle `Node.js` and those 3 files.

**Comment by loretoparisi** [comment]
> No, it's not possible with `wasm2native`, as it requires a JS engine. So at the end of the day, you need to bundle `Node.js` and those 3 files.

Right, but then I coud avoid completely NodeJS and use the C++ version [here](https://github.com/facebookresearch/fastText). They have the WebAssembly build with EMScripten...
https://github.com/facebookresearch/fastText/tree/main/webassembly

How it will work in that case?


Thank you!
