### ISSUE TITLE
[Documentation] Could more small examples be added?

### ISSUE THREAD

**Issue by rubyFeedback** [vshymanskyy/wasm2native#3]
Could more small examples be added?

A bit like an "actionable FAQ".

"How to turn this hello-world into a WASM application"

or how to respond to this button click-event, from WASM point of view;
how to interoperate with it from ruby, python etc...

I understand that time is limited, so I am really just asking on SMALL
and simple examples how to make things work from a practical
point of view. With WASM in general I found there is a lack of 
clear, concise and simple documentation + example, at the least
in ruby. Hopefully the whole WASM ecosystem can become better
in this regard, to avoid having to use StackOverflow all of the
time. :D

(Once people understand a specific part of software better, they
no longer need this basic information, so this is really more of
"getting new people on board of WASM".)

**Comment by vshymanskyy** [comment]
https://github.com/vshymanskyy/wasm2native/tree/afa64bee90b3483e8747f3533906a7332c588a6b?tab=readme-ov-file#usage-examples

**Comment by vshymanskyy** [comment]
Literally, this: https://github.com/vshymanskyy/wasm2native?tab=readme-ov-file#usage-examples
